INSERT INTO `privileges` (`id`, `name`, `description`, `apelido`, `ord`) VALUES
(3, 'access_analise', 'Acesso ao menu ANÁLISE (necessário para acessar qualquer item relacionado às analises)', 'Menu análise', 2000),
(28, 'access_analistas', 'Acesso aos analistas cadastrados no sistema.', 'Acessar analistas', 4030),
(32, 'access_anomalias', 'Acesso as Anomalias cadastradas.', 'Acessar anomalias', 4040),
(9, 'access_areassetores', 'Acesso à lista de áreas e setores da empresa selecionada.', 'Acesso lista de áreas e setores', 1010),
(36, 'access_componentes', 'Acesso aos Componentes cadastrados.', 'Acessar componentes', 4050),
(56, 'access_condicoes', 'Acesso as condições cadastradas.', 'Acessar condições', 5001),
(1, 'access_empresa', 'Acesso ao menu EMPRESA (necessário para acessar qualquer item relacionado à empresa)', 'Menu empresa', 999),
(16, 'access_equipamentos', 'Acesso à lista de equipamentos da empresa selecionada.', 'Acesso lista de equipamentos.', 1020),
(60, 'access_list_empresas', 'Acesso a lista de empresas do sistema', 'Acessar lista de empresas', 1000),
(61, 'access_print_osp', 'Permite ao usuário acessar a página da OSP com layout de impressão.\n', 'Imprimir OSP´s', 8004),
(40, 'access_recomendacoes', 'Acesso aos recomendações cadastradas.', 'Acessar recomendações', 4060),
(5, 'access_relatorios', 'Acesso ao menu RELATÓRIOS (necessário para acessar qualquer item relacionado aos relatórios)', 'Menu relatórios', 3000),
(27, 'access_roles', 'Acesso aos grupos de usuário do sistema.', 'Acesso grupos de usuário', 4020),
(20, 'access_rotas', 'Acesso à lista de rotas da empresa selecionada.', 'Acesso lista rotas', 1030),
(2, 'access_sistema', 'Acesso ao menu SISTEMA (necessário para acessar qualquer item relacionado ao sistema)', 'Menu sistema', 4000),
(44, 'access_tecnologias', 'Acesso as tecnologias cadastradas.', 'Acessar tecnologias', 4070),
(48, 'access_tiposinspecao', 'Acesso aos tipos de inspeção cadastradas.', 'Acessar tipos de inspeção', 4080),
(52, 'access_tipos_equipamento', 'Acesso aos tipos de equipamento cadastrados.', 'Acessar tipos de equipamento', 4090),
(24, 'access_usuarios_empresa', 'Permite acesso aos usuários da empresa, além de adicionar novos e editar seus dados.', 'Acesso usuários empresa', 1040),
(26, 'access_usuarios_sistema', 'Acesso aos usuários de sistema.', 'Acessar usuários sistema', 4010),
(29, 'add_analistas', 'Permite adicionar novos analistas no sistema.', 'Adicionar Analistas', 4031),
(33, 'add_anomalias', 'Permite adicionar novos anomalias.', 'Adicionar anomalias', 4041),
(10, 'add_areas', 'Permite adicionar novas áreas.', 'Adicionar Áreas', 1011),
(37, 'add_componentes', 'Permite adicionar novos componentes.', 'Adicionar componentes', 4051),
(57, 'add_condicoes', 'Permite adicionar novos condições.', 'Adicionar condições', 5002),
(6, 'add_empresas', 'Permite cadastrar novas empresas', 'Adicionar Empresas', 1001),
(17, 'add_equipamentos', 'Permite adicionar novos equipamentos.', 'Adicionar Equipamentos', 1021),
(41, 'add_recomendacoes', 'Permite adicionar novos recomendações.', 'Adicionar recomendações', 4061),
(23, 'add_rotas', 'Permite adicionar novas rotas.', 'Adicionar Rotas', 1033),
(13, 'add_setores', 'Permite adicionar setores.', 'Adicionar Setores', 1014),
(45, 'add_tecnologias', 'Permite adicionar novos tecnologias.', 'Adicionar tecnologias', 4071),
(53, 'add_tipos_equipamento', 'Permite adicionar novos tipos de equipamento.', 'Adicionar tipos de equipamento', 4091),
(49, 'add_tipos_inspecao', 'Permite adicionar novos tipos de inspeção.', 'Adicionar tipos de inspeção', 4081),
(64, 'contabilizar_os', 'Permite ao usuário contabilizar a ordem de serviço.', 'Contabilizar Ordem de serviço', 8002),
(30, 'edit_analistas', 'Permite editar os analistas existentes no sistema.', 'Editar Analistas', 4032),
(34, 'edit_anomalias', 'Permite editar as Anomalias existentes.', 'Editar anomalias', 4042),
(11, 'edit_areas', 'Permite editar Áreas.', 'Editar Áreas', 1012),
(38, 'edit_componentes', 'Permite editar os componentes existentes.', 'Editar componentes', 4052),
(58, 'edit_condicoes', 'Permite editar as condições existentes.', 'Editar condições', 5003),
(7, 'edit_empresas', 'Permite editar os dados de empresas existentes.', 'Editar Empresas', 1002),
(18, 'edit_equipamentos', 'Permite editar equipamentos.', 'Editar Equipamentos', 1022),
(42, 'edit_recomendacoes', 'Permite editar as recomendações existentes.', 'Editar recomendações', 4062),
(21, 'edit_rotas', 'Permite editar Rotas.', 'Editar Rotas', 1031),
(4, 'edit_self_account', 'Permite editar a própria conta.', 'Menu Conta', 6000),
(14, 'edit_setores', 'Permite editar setores.', 'Editar Setores', 1015),
(46, 'edit_tecnologias', 'Permite editar as tecnologias existentes.', 'Editar tecnologias', 4072),
(54, 'edit_tipos_equipamento', 'Permite editar os tipos de equipamento existentes.', 'Editar tipos de equipamento', 4092),
(50, 'edit_tipos_inspecao', 'Permite editar as tipos de inspeção existentes.', 'Editar tipos de inspeção', 4082),
(63, 'executar_os', 'Permite ao usuário executar a ordem de serviço.', 'Executar Ordem de serviço', 8001),
(65, 'finalizar_os', 'Permite ao usuário finalizar a ordem de serviço.', 'Finalizar Ordem de serviço', 8003),
(62, 'planejar_os', 'Permite ao usuário planejar a ordem de serviço.', 'Planejar Ordem de Serviço', 8000),
(31, 'remove_analistas', 'Permite remover os analistas existentes no sistema.', 'Remover Analistas', 4033),
(35, 'remove_anomalias', 'Permite remover as Anomalias existentes.', 'Remover anomalias', 4043),
(12, 'remove_areas', 'Permite remover áreas.', 'Remover Áreas', 1013),
(39, 'remove_componentes', 'Permite remover os componentes existentes.', 'Remover componentes', 4053),
(59, 'remove_condicoes', 'Permite remover as condições existentes.', 'Remover condições', 5004),
(8, 'remove_empresas', 'Permite remover empresas existentes.', 'Remover Empresas', 1003),
(19, 'remove_equipamentos', 'Permite remover equipamentos.', 'Remover Equipamentos', 1023),
(25, 'remove_grauderisco', 'Permite remover um item da lista de grau de risco.', 'Remover grau de risco', 2010),
(43, 'remove_recomendacoes', 'Permite remover as recomendações existentes.', 'Remover recomendações', 4063),
(22, 'remove_rotas', 'Permite remover Rotas.', 'Remover Rotas', 1032),
(15, 'remove_setores', 'Permite remover Setores.', 'Remover Setores', 1016),
(47, 'remove_tecnologias', 'Permite remover as tecnologias existentes.', 'Remover tecnologias', 4073),
(55, 'remove_tiposequipamento', 'Permite remover os tipos de equipamento existentes.', 'Remover tipos de equipamento', 4093),
(51, 'remove_tipos_inspecao', 'Permite remover as tipos de inspeção existentes.', 'Remover tipos de inspeção', 4083);