<?php defined('SYSPATH') OR die('No direct script access.');

return array(

	'ACCESS_ANALISE' => 'access_analise',
	'ACCESS_ANALISTAS' => 'access_analistas',
	'ACCESS_ANOMALIAS' => 'access_anomalias',
	'ACCESS_AREASSETORES' => 'access_areassetores',
	'ACCESS_COMPONENTES' => 'access_componentes',
	'ACCESS_CONDICOES' => 'access_condicoes',
	'ACCESS_EMPRESA' => 'access_empresa',
	'ACCESS_EQUIPAMENTOS' => 'access_equipamentos',
	'ACCESS_LIST_EMPRESAS' => 'access_list_empresas',
	'ACCESS_LIST_ROTAS' => 'access_list_rotas',
	'ACCESS_RECOMENDACOES' => 'access_recomendacoes',
	'ACCESS_RELATORIOS' => 'access_relatorios',
	'ACCESS_ROLES' => 'access_roles',
	'ACCESS_SISTEMA' => 'access_sistema',
	'ACCESS_TECNOLOGIAS' => 'access_tecnologias',
	'ACCESS_TIPOSEQUIPAMENTO' => 'access_tiposequipamento',
	'ACCESS_TIPOSINSPECAO' => 'access_tiposinspecao',
	'ACCESS_USUARIOS_EMPRESA' => 'access_usuarios_empresa',
	'ACCESS_USUARIOS_SISTEMA' => 'access_usuarios_sistema',
	'ADD_ANALISTAS' => 'add_analistas',
	'ADD_ANOMALIAS' => 'add_anomalias',
	'ADD_AREAS' => 'add_areas',
	'ADD_COMPONENTES' => 'add_componentes',
	'ADD_CONDICOES' => 'add_condicoes,',
	'ADD_EMPRESAS' => 'add_empresas',
	'ADD_EQUIPAMENTOS' => 'add_equipamentos',
	'ADD_RECOMENDACOES' => 'add_recomendacoes',
	'ADD_ROTAS' => 'add_rotas',
	'ADD_SETORES' => 'add_setores',
	'ADD_TECNOLOGIAS' => 'add_tecnologias',
	'ADD_TIPOSEQUIPAMENTO' => 'add_tiposequipamento',
	'ADD_TIPOSINSPECAO' => 'add_tiposinspecao',
	'EDIT_ANALISTAS' => 'edit_analistas',
	'EDIT_ANOMALIAS' => 'edit_anomalias',
	'EDIT_AREAS' => 'edit_areas',
	'EDIT_COMPONENTES' => 'edit_componentes',
	'EDIT_CONDICOES' => 'edit_condicoes',
	'EDIT_EMPRESAS' => 'edit_empresas',
	'EDIT_EQUIPAMENTOS' => 'edit_equipamentos',
	'EDIT_RECOMENDACOES' => 'edit_recomendacoes',
	'EDIT_ROTAS' => 'edit_rotas',
	'EDIT_SELF_ACCOUNT' => 'edit_self_account',
	'EDIT_SETORES' => 'edit_setores',
	'EDIT_TECNOLOGIAS' => 'edit_tecnologias',
	'EDIT_TIPOSEQUIPAMENTO' => 'edit_tiposequipamento',
	'EDIT_TIPOSINSPECAO' => 'edit_tiposinspecao',
	'REMOVE_ANALISTAS' => 'remove_analistas',
	'REMOVE_ANOMALIAS' => 'remove_anomalias',
	'REMOVE_AREAS' => 'remove_areas',
	'REMOVE_COMPONENTES' => 'remove_componentes',
	'REMOVE_CONDICOES' => 'remove_condicoes',
	'REMOVE_EMPRESAS' => 'remove_empresas',
	'REMOVE_EQUIPAMENTOS' => 'remove_equipamentos',
	'REMOVE_GRAUDERISCO' => 'remove_grauderisco',
	'REMOVE_RECOMENDACOES' => 'remove_recomendacoes',
	'REMOVE_ROTAS' => 'remove_rotas',
	'REMOVE_SETORES' => 'remove_setores',
	'REMOVE_TECNOLOGIAS' => 'remove_tecnologias',
	'REMOVE_TIPOSEQUIPAMENTO' => 'remove_tiposequipamento',
	'REMOVE_TIPOSINSPECAO' => 'remove_tiposinspecao'

);
